name: Publish external server 1 live

on:
  workflow_dispatch:
  push:
    tags:
    - v*

jobs:
  build:

    runs-on: wiser-ext-1-live

    steps:
    - uses: actions/checkout@v2
    
    - name: Restore dependencies
      run: dotnet restore

    - name: Add NuGet Sources
      run: dotnet nuget add source --username GilianJuice --password ${{ secrets.HAPPYGEEKSNUGET }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/happy-geeks/index.json"

    - name: Add plugins FrontEnd
      run: dotnet add FrontEnd package GeeksCoreLibrary.Components.Configurator

    - name: Add plugins API
      run: dotnet add Api package GeeksCoreLibrary.Components.Configurator
      
    - name: Copy partner styles
      run: Copy-Item -Path "${{ secrets.PARTNER_STYLES_LOCATION }}\*" -Destination "${{ secrets.WORKER_LOCATION_EXT_1_LIVE }}\wiser\wiser\FrontEnd\Core\Css\partner" -Recurse
      
    - name: Build
      run: dotnet build --no-restore
      
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
      
    - name: Enable maintenance notice API
      run: Rename-Item -Path "${{ secrets.PUBLISH_LOCATION_API_LIVE }}\_App_Offline.htm" -NewName "App_Offline.htm"
      
    - name: Enable maintenance notice FrontEnd
      run: Rename-Item -Path "${{ secrets.PUBLISH_LOCATION_FRONT_END_LIVE }}\_App_Offline.htm" -NewName "App_Offline.htm"

    - name: dotnet publish API
      run: |
        dotnet publish API -c Release -o "${{ secrets.PUBLISH_LOCATION_API_LIVE }}" --self-contained true  -r win-x64 /p:EnvironmentName=Live

    - name: Install NPM modules
      run: npm install
      working-directory: 'FrontEnd'

    - name: Activate Kendo UI License
      run: npx kendo-ui-license activate
      working-directory: 'FrontEnd'
      env:
        KENDO_UI_LICENSE: ${{ secrets.KENDO_UI_LICENSE }}
                
    - name: Compile scripts and styles with webpack
      run: node_modules\.bin\webpack --mode=production
      working-directory: 'FrontEnd'

    - name: dotnet publish front-end
      run: |
        dotnet publish FrontEnd -c Release -o "${{ secrets.PUBLISH_LOCATION_FRONT_END_LIVE }}" --self-contained true  -r win-x64 /p:EnvironmentName=Live
      
    - name: Disable maintenance notice API
      if: ${{ always() }}
      run: Rename-Item -Path "${{ secrets.PUBLISH_LOCATION_API_LIVE }}\App_Offline.htm" -NewName "_App_Offline.htm"
      
    - name: Disable maintenance notice FrontEnd
      if: ${{ always() }}
      run: Rename-Item -Path "${{ secrets.PUBLISH_LOCATION_FRONT_END_LIVE }}\App_Offline.htm" -NewName "_App_Offline.htm"

    - name: Remove NuGet Sources
      if: ${{ always() }}
      run: dotnet nuget remove source github
