name: Publish live server 1

on:
  push:
    tags:
    - v*

jobs:
  build:

    runs-on: wiser-1

    steps:
    - uses: actions/checkout@v4

    - name: Add NuGet Sources
      run: dotnet nuget add source --username ${{ vars.NUGET_USERNAME }} --password ${{ secrets.HAPPYGEEKSNUGET }} --store-password-in-clear-text --name HappyHorizon "${{ vars.NUGET_SOURCE }}"

    - name: Add GCLC package
      run: |
            $INSTALLED_PACKAGES = dotnet list Api package --format json
            $GCL_INSTALLED_VERSION = $INSTALLED_PACKAGES | ConvertFrom-Json | Select-Object -ExpandProperty projects | ForEach-Object { $_.frameworks | ForEach-Object { $_.topLevelPackages | Where-Object { $_.id -eq "GeeksCoreLibrary" } | Select-Object -ExpandProperty requestedVersion } }
            echo "Used GCL version: $GCL_INSTALLED_VERSION"
            dotnet add FrontEnd package GeeksCoreLibrary.Components.Configurator --version $GCL_INSTALLED_VERSION
            dotnet add Api package GeeksCoreLibrary.Components.Configurator --version $GCL_INSTALLED_VERSION

    - name: Copy partner styles
      run: Copy-Item -Path "${{ secrets.PARTNER_STYLES_LOCATION }}\*" -Destination "${{ secrets.WORKER_LOCATION }}\wiser\wiser\FrontEnd\Core\Css\partner" -Recurse

    - name: Build
      run: dotnet build --no-restore

    #- name: Test
    #  run: dotnet test --no-build --verbosity normal

    - name: Enable maintenance notice API
      run: Rename-Item -Path "${{ secrets.PUBLISH_LOCATION_API_LIVE }}\_App_Offline.htm" -NewName "App_Offline.htm"

    - name: Enable maintenance notice FrontEnd
      run: Rename-Item -Path "${{ secrets.PUBLISH_LOCATION_FRONT_END_LIVE }}\_App_Offline.htm" -NewName "App_Offline.htm"

    - name: dotnet publish API
      run: |
        dotnet publish API -c Release -o "${{ secrets.PUBLISH_LOCATION_API_LIVE }}" --self-contained true  -r win-x64 /p:EnvironmentName=Live

    - name: Install NPM modules
      run: npm install
      working-directory: 'FrontEnd'

    - name: Activate Kendo UI License
      run: npx kendo-ui-license activate
      working-directory: 'FrontEnd'
      env:
        KENDO_UI_LICENSE: ${{ secrets.KENDO_UI_LICENSE }}

    - name: Compile scripts and styles with webpack
      run: node_modules\.bin\webpack --mode=production
      working-directory: 'FrontEnd'

    - name: dotnet publish front-end
      run: |
        dotnet publish FrontEnd -c Release -o "${{ secrets.PUBLISH_LOCATION_FRONT_END_LIVE }}" --self-contained true  -r win-x64 /p:EnvironmentName=Live

    - name: Disable maintenance notice API
      if: ${{ always() }}
      run: Rename-Item -Path "${{ secrets.PUBLISH_LOCATION_API_LIVE }}\App_Offline.htm" -NewName "_App_Offline.htm"

    - name: Disable maintenance notice FrontEnd
      if: ${{ always() }}
      run: Rename-Item -Path "${{ secrets.PUBLISH_LOCATION_FRONT_END_LIVE }}\App_Offline.htm" -NewName "_App_Offline.htm"

    - name: Remove NuGet Sources
      if: ${{ always() }}
      run: dotnet nuget remove source HappyHorizon