-- Add entity properties for the product api settings.
INSERT INTO `wiser_entity` (`name`, `module_id`, `accepted_childtypes`, `icon`, `icon_add`, `show_in_tree_view`, `show_in_search`, `show_overview_tab`, `save_title_as_seo`, `show_title_field`, `friendly_name`, `save_history`, `default_ordering`, `icon_expanded`, `dedicated_table_prefix`, `delete_action`) VALUES ('ProductsApiSettings', 700, '', 'icon-git', 'icon-add', 0, 1, 1, 0, 0, 'Products Api settings', 1, 'link_ordering', 'icon-git', '', 'archive') ON DUPLICATE KEY UPDATE id=id;

-- Add the properties for the product api settings.
INSERT INTO `wiser_entityproperty` (`module_id`, `entity_name`, `link_type`, `visible_in_overview`, `overview_width`, `tab_name`, `group_name`, `inputtype`, `display_name`, `property_name`, `explanation`, `ordering`, `regex_validation`, `mandatory`, `readonly`, `default_value`, `width`, `height`, `options`, `data_query`, `action_query`, `search_query`, `search_count_query`, `grid_delete_query`, `grid_insert_query`, `grid_update_query`, `depends_on_field`, `depends_on_operator`, `depends_on_value`, `language_code`, `custom_script`, `also_save_seo_value`, `depends_on_action`, `save_on_change`, `extended_explanation`, `label_style`, `label_width`, `enable_aggregation`, `aggregate_options`, `access_key`, `visibility_path_regex`) VALUES (0, 'ProductsApiSettings', 0, 0, 100, 'General', '', 'input', 'Product entity name', 'product_entity_name', 'Deze naam word gebruikt om te weten welke wiser items producten zijn (`product`, `artikel` etc.) .', 1, '', 0, 0, 'Product', 50, 0, '', '', '', '', '', '', '', '', '', NULL, '', '', '', 0, NULL, 0, 0, 'normal', '0', 0, '', '', '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `wiser_entityproperty` (`module_id`, `entity_name`, `link_type`, `visible_in_overview`, `overview_width`, `tab_name`, `group_name`, `inputtype`, `display_name`, `property_name`, `explanation`, `ordering`, `regex_validation`, `mandatory`, `readonly`, `default_value`, `width`, `height`, `options`, `data_query`, `action_query`, `search_query`, `search_count_query`, `grid_delete_query`, `grid_insert_query`, `grid_update_query`, `depends_on_field`, `depends_on_operator`, `depends_on_value`, `language_code`, `custom_script`, `also_save_seo_value`, `depends_on_action`, `save_on_change`, `extended_explanation`, `label_style`, `label_width`, `enable_aggregation`, `aggregate_options`, `access_key`, `visibility_path_regex`) VALUES (0, 'ProductsApiSettings', 0, 0, 100, 'General', '', 'numeric-input', 'Minimale refresh tijd', 'minimal_refresh_cooldown', 'Dit is de minimale tijd die voorbij moet zijn voordat een product opnieuw ge-refresh kan worden( in minuten)', 1, '', 0, 0, '180', 50, 0, '{\"decimals\":0, \"format\":\ "#\"}', '', '', '', '', '', '', '', '', NULL, '', '', '', 0, NULL, 0, 0, 'normal', '0', 0, '', '', '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `wiser_entityproperty` (`module_id`, `entity_name`, `link_type`, `visible_in_overview`, `overview_width`, `tab_name`, `group_name`, `inputtype`, `display_name`, `property_name`, `explanation`, `ordering`, `regex_validation`, `mandatory`, `readonly`, `default_value`, `width`, `height`, `options`, `data_query`, `action_query`, `search_query`, `search_count_query`, `grid_delete_query`, `grid_insert_query`, `grid_update_query`, `depends_on_field`, `depends_on_operator`, `depends_on_value`, `language_code`, `custom_script`, `also_save_seo_value`, `depends_on_action`, `save_on_change`, `extended_explanation`, `label_style`, `label_width`, `enable_aggregation`, `aggregate_options`, `access_key`, `visibility_path_regex`) VALUES (0, 'ProductsApiSettings', 0, 0, 100, 'General', '', 'textbox', 'product ids query', 'product_ids_query', 'Deze query word gebruikt om te weten welke wiser items voor de product api gebruikt moeten worden.', 1, '', 0, 0, 'SELECT id FROM wiser_item WHERE entity_type=\"product\" AND published_environment > 0;', 50, 0, '', '', '', '', '', '', '', '', '', NULL, '', '', '', 0, NULL, 0, 0, 'normal', '0', 0, '', '', '') ON DUPLICATE KEY UPDATE id=id;

INSERT INTO `wiser_entityproperty` (`module_id`, `entity_name`, `link_type`, `visible_in_overview`, `overview_width`, `tab_name`, `group_name`, `inputtype`, `display_name`, `property_name`, `explanation`, `ordering`, `regex_validation`, `mandatory`, `readonly`, `default_value`, `width`, `height`, `options`, `data_query`, `action_query`, `search_query`, `search_count_query`, `grid_delete_query`, `grid_insert_query`, `grid_update_query`, `depends_on_field`, `depends_on_operator`, `depends_on_value`, `language_code`, `custom_script`, `also_save_seo_value`, `depends_on_action`, `save_on_change`, `extended_explanation`, `label_style`, `label_width`, `enable_aggregation`, `aggregate_options`, `access_key`, `visibility_path_regex`) VALUES (0, 'ProductsApiSettings', 0, 0, 100, 'product defaults', '', 'combobox', 'DataSourceType', 'datasource_type', 'Het default datasource type, dit bepaald welke output ge-called word per product', 1, '', 0, 0, '0', 70, 0, '{ \"useDropDownList\": true, \"dataSource\": [ { \"name\": \"Static\", \"id\": \"0\" }, { \"name\": \"Query\", \"id\": \"1\" }, { \"name\": \"StyledOutput\", \"id\": \"2\" } ] }', '', '', '', '', '', '', '', '', NULL, '', '', '', 0, NULL, 0, 0, 'normal', '0', 0, '', '', '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `wiser_entityproperty` (`module_id`, `entity_name`, `link_type`, `visible_in_overview`, `overview_width`, `tab_name`, `group_name`, `inputtype`, `display_name`, `property_name`, `explanation`, `ordering`, `regex_validation`, `mandatory`, `readonly`, `default_value`, `width`, `height`, `options`, `data_query`, `action_query`, `search_query`, `search_count_query`, `grid_delete_query`, `grid_insert_query`, `grid_update_query`, `depends_on_field`, `depends_on_operator`, `depends_on_value`, `language_code`, `custom_script`, `also_save_seo_value`, `depends_on_action`, `save_on_change`, `extended_explanation`, `label_style`, `label_width`, `enable_aggregation`, `aggregate_options`, `access_key`, `visibility_path_regex`) VALUES (0, 'ProductsApiSettings', 0, 0, 100, 'product defaults', '', 'textbox', 'static text', 'datasource_static', 'De static text die gebruikt moet worden.', 2, '', 0, 0, '{ \"name\": \"notset\"}', 30, 0, '', '', '', '', '', '', '', '', 'datasource_type', 'eq', '0', '', '', 0, NULL, 0, 0, 'normal', '0', 0, '', '', '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `wiser_entityproperty` (`module_id`, `entity_name`, `link_type`, `visible_in_overview`, `overview_width`, `tab_name`, `group_name`, `inputtype`, `display_name`, `property_name`, `explanation`, `ordering`, `regex_validation`, `mandatory`, `readonly`, `default_value`, `width`, `height`, `options`, `data_query`, `action_query`, `search_query`, `search_count_query`, `grid_delete_query`, `grid_insert_query`, `grid_update_query`, `depends_on_field`, `depends_on_operator`, `depends_on_value`, `language_code`, `custom_script`, `also_save_seo_value`, `depends_on_action`, `save_on_change`, `extended_explanation`, `label_style`, `label_width`, `enable_aggregation`, `aggregate_options`, `access_key`, `visibility_path_regex`) VALUES (0, 'ProductsApiSettings', 0, 0, 100, 'product defaults', '', 'numeric-input', 'query id', 'datasource_query', 'De id van de query die gebruikt moet worden.', 2, '', 0, 0, '', 50, 0, '{\"decimals\":0, \"format\":\ "#\"}', '', '', '', '', '', '', '', 'datasource_type', 'eq', '1', '', '', 0, NULL, 0, 0, 'normal', '0', 0, '', '', '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `wiser_entityproperty` (`module_id`, `entity_name`, `link_type`, `visible_in_overview`, `overview_width`, `tab_name`, `group_name`, `inputtype`, `display_name`, `property_name`, `explanation`, `ordering`, `regex_validation`, `mandatory`, `readonly`, `default_value`, `width`, `height`, `options`, `data_query`, `action_query`, `search_query`, `search_count_query`, `grid_delete_query`, `grid_insert_query`, `grid_update_query`, `depends_on_field`, `depends_on_operator`, `depends_on_value`, `language_code`, `custom_script`, `also_save_seo_value`, `depends_on_action`, `save_on_change`, `extended_explanation`, `label_style`, `label_width`, `enable_aggregation`, `aggregate_options`, `access_key`, `visibility_path_regex`) VALUES (0, 'ProductsApiSettings', 0, 0, 100, 'product defaults', '', 'numeric-input', 'styledoutput id', 'datasource_styledoutput', 'De id van de styled output die gebruikt moet worden.', 2, '', 0, 0, '', 50, 0, '{\"decimals\":0, \"format\":\ "#\"}', '', '', '', '', '', '', '', 'datasource_type', 'eq', '2', '', '', 0, NULL, 0, 0, 'normal', '0', 0, '', '', '') ON DUPLICATE KEY UPDATE id=id;

-- Add link info so we can see the settings under our folder.
INSERT INTO `wiser_link` (`type`, `destination_entity_type`, `connected_entity_type`, `name`, `show_in_tree_view`, `show_in_data_selector`, `relationship`, `duplication`, `use_item_parent_id`, `use_dedicated_table`, `cascade_delete`) VALUES (1, 'map', 'ProductsApiSettings', 'ProductsApiSettingsToCMap', 1, 0, 'one-to-many', 'none', 1, 0, 0);

-- And add it to the accepted childtypes of the 'map' in 'stamgegevens'.
UPDATE wiser_entity SET accepted_childtypes = CONCAT(accepted_childtypes, ',ProductsApiSettings') WHERE name = 'map' AND module_id = '700' AND FIND_IN_SET('ProductsApiSettings', accepted_childtypes) = 0;

-- Product default Api settings will live in the "stamgegevens" module, add it there.
INSERT INTO `wiser_item` (entity_type, moduleid, title) VALUES ('map', '700', 'Products api settings');
SET @settingsFolderId = LAST_INSERT_ID();    
    
-- Add the link to the settings folder in the wiser link.
INSERT INTO `wiser_itemlink` (`item_id`,`destination_item_id`, `type`) VALUES (@settingsFolderId, 0,1);

-- Add an item for the settings.
INSERT INTO `wiser_item` (unique_uuid, entity_type, parent_item_id, moduleid, title, added_by) VALUES ('default_products_api_settings', 'ProductsApiSettings', @settingsFolderId, 700, 'Standaard product api instellingen', 'Wiser');
SET @newItemId = LAST_INSERT_ID();

-- Add the default settings so we have details filled in and that they can be used right way (instead of after the first time someone edits/saves them.    
INSERT INTO `wiser_itemdetail` (`item_id`, `key`, `value`) VALUES (@newItemId, 'datasource_static', '{ \"name\": \"notset\"}');
INSERT INTO `wiser_itemdetail` (`item_id`, `key`, `value`) VALUES (@newItemId, 'datasource_type', '0');
INSERT INTO `wiser_itemdetail` (`item_id`, `key`, `value`) VALUES (@newItemId, 'minimal_refresh_cooldown', '180');
INSERT INTO `wiser_itemdetail` (`item_id`, `key`, `value`) VALUES (@newItemId, 'product_entity_name', 'Product');
INSERT INTO `wiser_itemdetail` (`item_id`, `key`, `value`) VALUES (@newItemId, 'product_ids_query', 'SELECT id FROM wiser_item WHERE entity_type=\"product\" AND published_environment > 0;');

-- Add the wiser_table_changes entry.
INSERT IGNORE INTO `wiser_table_changes` (`name`, `last_update`) VALUES ('wiser_add_products_api_settings', NOW());